FROM python:3.9
USER root

RUN apt-get update
RUN pip install --upgrade pip

RUN python -m pip install numpy
RUN python -m pip install pandas
RUN python -m pip install matplotlib
RUN python -m pip install jupyterlab
RUN python -m pip install scipy
RUN python -m pip install seaborn
